### ISSUE TITLE
EXPO SDK 52: Couldn't find a navigation object

### ISSUE THREAD

**Issue by oscklm** [PostHog/posthog-js-lite#336]
## Bug description
After upgrading to latest suggested versions of expo packages. I'm getting this bug:

```ts
 (NOBRIDGE) ERROR  Warning: Error: Couldn't find a navigation object. Is your component inside NavigationContainer?

This error is located at:
    in PostHogNavigationHook (created by PostHogProvider)
    in RCTView (created by View)
    in View (created by PostHogProvider)
    in PostHogProvider (created by PosthogProvider)
    in PosthogProvider (created by RootLayout)
    in ConvexProvider (created by ConvexProviderWithAuth)
    in ConvexProviderWithAuth (created by ConvexProviderWithClerk)
    in ConvexProviderWithClerk (created by ConvexClientProvider)
    in SWRConfig (created by OrganizationProvider)
    in OrganizationProvider (created by ClerkContextProvider)
    in ClerkContextProvider (created by ClerkProviderBase)
    in ClerkProviderBase (created by ClerkProvider)
    ...
```

## How to reproduce

1. Run npx-doctor in a sdk 52 expo project
2. Install recommended packages
3. Boot up a dev server and run the app in simulator or on physical device

## Related sub-libraries

- [ ] All of them
- [ ] posthog-web
- [ ] posthog-node
- [x] posthog-react-native

## Additional context
![Simulator Screenshot - iPhone 16 Pro - 2025-01-12 at 20 56 23](https://github.com/user-attachments/assets/e094071d-5b91-44d8-8d4e-81c8eb0b2743)

**Comment by marandaneto** [comment]
Hello @oscklm thanks
Can you share the PH SDK version the the PH SDK code snippets such as setting up the `PostHogProvider` and so on?
Are you using any navigation lib such as react-native-navigation, @react-navigation/native or something else? which version?

Thanks.

**Comment by oscklm** [comment]
Hey sorry for missing that information. 

I just tried running expo-doctor again, to get the missing info about versions etc. and the issue seems to have been resolved. I tried figuring out what might have been the reason to it working now, compared to earlier. But to no luck.

Closing this issue now ✌️

**Comment by iamrestrepo** [comment]
HI! I am actually having this exact issue after upgrading to `Expo's SDK 52` and expo-doctor was not the solution for me. I wonder if anyone else has run into it. 

- `"posthog-react-native": "~3.9.0"`
- `"@react-navigation/native": "^6.1.6"`

- This is how I am setting up PH: 

````
import PostHog from 'posthog-react-native'

const postHogApiKey = 'xxxxxx';


export const posthog = new PostHog(postHogApiKey);
````

**Comment by muhajirdev** [comment]
got the same issue as well

**Comment by muhajirdev** [comment]
Got the same issue as well, did you managed to fix it @iamrestrepo

**Comment by muhajirdev** [comment]
```
import { useNavigation } from "@react-navigation/native";

export default function PersonalAssistantLayout() {
  const navigation = useNavigation();
```

It seems that `useNavigation` is the culprit. `expo-router` expose its own `useNavigation`

**Comment by muhajirdev** [comment]
I fixed this issue by creating my own tracker

```
import {
  useGlobalSearchParams,
  useNavigation,
  usePathname,
  useRouter,
} from "expo-router";
import { usePostHog } from "posthog-react-native";
import { useCallback, useEffect } from "react";

function useNavigationTracker(): void {
  const posthog = usePostHog();

  const router = useRouter();

  const currentRouteName = usePathname();
  const params = useGlobalSearchParams();

  const trackRoute = useCallback((): void => {
    if (currentRouteName) {
      posthog.screen(currentRouteName, params);
    }
  }, [currentRouteName, params, posthog]);

  useEffect(() => {
    // NOTE: The navigation stacks may not be fully rendered initially. This means the first route can be missed (it doesn't update useNavigationState)
    // If missing we simply wait a tick and call it again.
    if (!router) {
      setTimeout(trackRoute, 1);
      return;
    }
    trackRoute();
  }, [router, trackRoute]);
}

export const PosthogNavigationHook = () => {
  useNavigationTracker();
  return null;
};

```

```
   <PostHogProvider
      apiKey={POSTHOG_API_KEY}
      autocapture={{
        captureScreens: false, // Screen events are handled differently for react-native-navigation
        captureLifecycleEvents: false, // Lifecycle events are handled differently for react-native-navigation
        captureTouches: true,
      }}
      options={{
        host: "https://us.i.posthog.com",
      }}
    >
```

**Comment by marandaneto** [comment]
https://github.com/PostHog/posthog-js-lite/blob/63f3881d9869c4171ab855dd552fba2a16600cbe/posthog-react-native/src/hooks/useNavigationTracker.ts#L20-L21
can you raise a new issue with more context? why would we use `useNavigation` from expo router if this is for `@react-navigation/native`

**Comment by fbeccaceci** [comment]
For me the problem is that `OptionalReactNativeNavigation` hooks do not work if react navigation is imported with a `require('@react-navigation/native')`

I tried manually passing the navigation ref but this doesn't solve the problem since it removes the use of the useNavigation hook but still throws the error on useNavigationState

**Comment by fbeccaceci** [comment]
```
diff --git a/lib/posthog-react-native/src/hooks/useNavigationTracker.js b/lib/posthog-react-native/src/hooks/useNavigationTracker.js
index 171a57f0e772817d1d567d90d63d57033e69ccd0..96068abf3721ba32a8ee3462cb7169a4a44f79e2 100644
--- a/lib/posthog-react-native/src/hooks/useNavigationTracker.js
+++ b/lib/posthog-react-native/src/hooks/useNavigationTracker.js
@@ -1 +1,103 @@
-"use strict";Object.defineProperty(exports,"__esModule",{value:true});exports.useNavigationTracker=void 0;var _react=require("react");var _OptionalReactNativeNavigation=require("../optional/OptionalReactNativeNavigation");var _usePostHog=require("./usePostHog");function _useNavigationTrackerDisabled(){return;}function _useNavigationTracker(options,navigationRef,client){var contextClient=(0,_usePostHog.usePostHog)();var posthog=client||contextClient;if(!_OptionalReactNativeNavigation.OptionalReactNativeNavigation){throw new Error('No OptionalReactNativeNavigation');}var routes=_OptionalReactNativeNavigation.OptionalReactNativeNavigation.useNavigationState(function(state){return state===null||state===void 0?void 0:state.routes;});var navigation=navigationRef||_OptionalReactNativeNavigation.OptionalReactNativeNavigation.useNavigation();var trackRoute=(0,_react.useCallback)(function(){var _a,_b,_c;if(!navigation){return;}var currentRoute=undefined;try{var isReady=false;try{isReady=navigation.isReady();}catch(error){isReady=true;}if(!isReady){return;}currentRoute=navigation.getCurrentRoute();}catch(error){return;}if(!currentRoute){return;}var _currentRoute=currentRoute,state=_currentRoute.state;var _currentRoute2=currentRoute,name=_currentRoute2.name,params=_currentRoute2.params;if((_a=state===null||state===void 0?void 0:state.routes)===null||_a===void 0?void 0:_a.length){var route=state.routes[state.routes.length-1];name=route.name;params=route.params;}var currentRouteName=((_b=options===null||options===void 0?void 0:options.routeToName)===null||_b===void 0?void 0:_b.call(options,name,params))||name||'Unknown';if(currentRouteName){var properties=(_c=options===null||options===void 0?void 0:options.routeToProperties)===null||_c===void 0?void 0:_c.call(options,currentRouteName,params);posthog.screen(currentRouteName,properties);}},[navigation,options,posthog]);(0,_react.useEffect)(function(){if(!routes){setTimeout(trackRoute,1);return;}trackRoute();},[routes,trackRoute]);}var useNavigationTracker=exports.useNavigationTracker=_OptionalReactNativeNavigation.OptionalReactNativeNavigation?_useNavigationTracker:_useNavigationTrackerDisabled;
\ No newline at end of file
+"use strict";
+Object.defineProperty(exports, "__esModule", { value: true });
+exports.useNavigationTracker = void 0;
+var _react = require("react");
+var _OptionalReactNativeNavigation = require("../optional/OptionalReactNativeNavigation");
+var _usePostHog = require("./usePostHog");
+var _useSyncExternalStore = require("use-sync-external-store/with-selector");
+function _useNavigationTrackerDisabled() {
+    return;
+}
+function _useNavigationTracker(options, navigationRef, client) {
+    var contextClient = (0, _usePostHog.usePostHog)();
+    var posthog = client || contextClient;
+    if (!_OptionalReactNativeNavigation.OptionalReactNativeNavigation) {
+        throw new Error("No OptionalReactNativeNavigation");
+    }
+
+    const useNavigationState = navigationRef 
+      ? createUseNavigationStateFromRef(navigationRef) 
+      : _OptionalReactNativeNavigation.OptionalReactNativeNavigation.useNavigationState;
+
+    var routes = useNavigationState(function (state) {
+        return state === null || state === void 0 ? void 0 : state.routes;
+    });
+    var navigation = navigationRef || _OptionalReactNativeNavigation.OptionalReactNativeNavigation.useNavigation();
+    var trackRoute = (0, _react.useCallback)(
+        function () {
+            var _a, _b, _c;
+            if (!navigation) {
+                return;
+            }
+            var currentRoute = undefined;
+            try {
+                var isReady = false;
+                try {
+                    isReady = navigation.isReady();
+                } catch (error) {
+                    isReady = true;
+                }
+                if (!isReady) {
+                    return;
+                }
+                currentRoute = navigation.getCurrentRoute();
+            } catch (error) {
+                return;
+            }
+            if (!currentRoute) {
+                return;
+            }
+            var _currentRoute = currentRoute,
+                state = _currentRoute.state;
+            var _currentRoute2 = currentRoute,
+                name = _currentRoute2.name,
+                params = _currentRoute2.params;
+            if ((_a = state === null || state === void 0 ? void 0 : state.routes) === null || _a === void 0 ? void 0 : _a.length) {
+                var route = state.routes[state.routes.length - 1];
+                name = route.name;
+                params = route.params;
+            }
+            var currentRouteName = ((_b = options === null || options === void 0 ? void 0 : options.routeToName) === null || _b === void 0 ? void 0 : _b.call(options, name, params)) || name || "Unknown";
+            if (currentRouteName) {
+                var properties = (_c = options === null || options === void 0 ? void 0 : options.routeToProperties) === null || _c === void 0 ? void 0 : _c.call(options, currentRouteName, params);
+                posthog.screen(currentRouteName, properties);
+            }
+        },
+        [navigation, options, posthog]
+    );
+    (0, _react.useEffect)(
+        function () {
+            if (!routes) {
+                setTimeout(trackRoute, 1);
+                return;
+            }
+            trackRoute();
+        },
+        [routes, trackRoute]
+    );
+}
+var useNavigationTracker = (exports.useNavigationTracker = _OptionalReactNativeNavigation.OptionalReactNativeNavigation ? _useNavigationTracker : _useNavigationTrackerDisabled);
+
+function createUseNavigationStateFromRef(navigation) {
+  return function useNavigationStateFromRef(selector) {
+    const subscribe = _react.useCallback(
+      (callback) => {
+        const unsubscribe = navigation.addListener("state", callback);
+
+        return unsubscribe;
+      },
+      [navigation]
+    );
+
+    const getState = _react.useCallback(() => {
+      if (!navigation.isReady()) return undefined;
+
+      return navigation.getState();
+    }, [navigation]);
+
+    const value = _useSyncExternalStore.useSyncExternalStoreWithSelector(subscribe, getState, getState, selector);
+
+    return value;
+  };
+}
+

```

I managed to make useNavigationState read from navigationRef if you provide one using this patch everything works for me

I just unminified the target js file and patched it with bun patch, not mergable to the original repo but gives the idea
